/**
 * MilkyWay Platform Service Interfaces
 * 
 * IMPORTANT ARCHITECTURAL DIRECTIVE:
 * These interfaces define the strict contract for backend interaction.
 * In development / demo preview, seed implementations satisfy these contracts.
 * In production:
 * - Event queries dispatch to BigQuery via Cloud Run REST endpoints.
 * - Investigation cases, alerts, and officer notes persist to Cloud Firestore.
 * - Future AI briefs query the Google ADK Investigation Agent via an MCP Server.
 */

import {
  Batch,
  SupplyChainEvent,
  Anomaly,
  InvestigationCase,
  OfficerNote,
  Facility,
  Vehicle,
  ActiveAlert,
  Officer
} from '../types/models';

export interface BatchFilterOptions {
  status?: string;
  facilityId?: string;
  minDiscrepancyLitres?: number;
  hasAnomaliesOnly?: boolean;
  searchQuery?: string;
}

export interface SupplyChainJournalService {
  /**
   * Queries the append-only supply-chain event journal.
   * PRODUCTION: Calls BigQuery REST endpoint on Cloud Run.
   */
  getRecentEvents(limit?: number): Promise<SupplyChainEvent[]>;
  getEventsForBatch(batchId: string): Promise<SupplyChainEvent[]>;
  getBatches(filters?: BatchFilterOptions): Promise<Batch[]>;
  getBatchById(batchId: string): Promise<Batch | null>;
  
  /**
   * NOTE: Supply chain events are append-only.
   * There are intentionally NO updateEvent or deleteEvent methods in this contract.
   */
  appendCompensatingEvent(event: Omit<SupplyChainEvent, 'eventId' | 'cryptographicHash' | 'previousEventHash'>): Promise<SupplyChainEvent>;
}

export interface InvestigationService {
  /**
   * Manages investigation cases and evidence dossiers.
   * PRODUCTION: Calls Google Cloud Firestore with role-based access rules.
   */
  getPriorityInvestigations(): Promise<InvestigationCase[]>;
  getAllCases(statusFilter?: string): Promise<InvestigationCase[]>;
  getCaseById(caseId: string): Promise<InvestigationCase | null>;
  getAnomalies(limit?: number): Promise<Anomaly[]>;
  
  /**
   * Appends an immutable officer note to an investigation case.
   */
  addOfficerNote(caseId: string, note: Omit<OfficerNote, 'id' | 'createdAt'>): Promise<OfficerNote>;
  
  /**
   * Updates case triage status (e.g. escalating for physical inspection).
   */
  updateCaseStatus(caseId: string, status: InvestigationCase['status'], officerId: string): Promise<boolean>;
}

export interface AlertService {
  /**
   * Manages real-time alerts generated by the deterministic anomaly engine.
   */
  getActiveAlerts(): Promise<ActiveAlert[]>;
  dismissAlert(alertId: string): Promise<boolean>;
}

export interface FacilityVehicleService {
  getFacilities(): Promise<Facility[]>;
  getFacilityById(facilityId: string): Promise<Facility | null>;
  getVehicles(): Promise<Vehicle[]>;
  getVehicleById(vehicleId: string): Promise<Vehicle | null>;
}

export interface OfficerAuthService {
  getCurrentOfficer(): Promise<Officer | null>;
  loginAsOfficer(officerId: string): Promise<Officer>;
  logout(): Promise<void>;
}
