import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import {
  AlertTriangle,
  Filter,
  CheckCircle2,
  ExternalLink,
  ShieldAlert,
  Clock,
  ArrowRight
} from 'lucide-react';
import { alertService } from '../../services';
import { ActiveAlert } from '../../types/models';

export const AlertsPage: React.FC = () => {
  const [alerts, setAlerts] = useState<ActiveAlert[]>([]);
  const [severityFilter, setSeverityFilter] = useState<string>('ALL');

  useEffect(() => {
    async function loadAlerts() {
      try {
        const data = await alertService.getActiveAlerts();
        setAlerts(data);
      } catch (err) {
        console.error('Failed to load alerts:', err);
      }
    }
    loadAlerts();
  }, []);

  const handleDismiss = async (alertId: string) => {
    await alertService.dismissAlert(alertId);
    setAlerts(prev => prev.map(a => a.id === alertId ? { ...a, isRead: true } : a));
  };

  const filtered = alerts.filter(a => {
    if (severityFilter === 'ALL') return true;
    return a.severity === severityFilter;
  });

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <AlertTriangle className="w-5 h-5 text-[#9E4939]" />
            <h1 className="text-2xl font-bold font-sans text-[#202521]">
              Active Anomaly Alerts
            </h1>
          </div>
          <p className="text-xs text-[#202521]/70 mt-1 font-normal">
            Real-time automated flags generated by deterministic mass-balance and velocity calculations.
          </p>
        </div>

        <div className="flex items-center gap-2 text-xs font-mono bg-[#FFFDF7] p-1 rounded-lg border border-[#202521]/15">
          {['ALL', 'CRITICAL', 'WARNING', 'ADVISORY'].map((sev) => (
            <button
              key={sev}
              onClick={() => setSeverityFilter(sev)}
              className={`px-3 py-1 rounded text-[11px] font-medium transition-colors cursor-pointer ${
                severityFilter === sev
                  ? 'bg-[#26352D] text-[#FFFDF7] font-bold'
                  : 'text-[#202521] hover:bg-[#F4F1E8]'
              }`}
            >
              {sev}
            </button>
          ))}
        </div>
      </div>

      <div className="space-y-3">
        {filtered.map((alert) => {
          const isCrit = alert.severity === 'CRITICAL';
          const isWarn = alert.severity === 'WARNING';
          return (
            <div
              key={alert.id}
              className={`bg-[#FFFDF7] p-5 rounded-xl border transition-all shadow-xs ${
                isCrit
                  ? 'border-[#9E4939]/40'
                  : isWarn
                  ? 'border-[#B78632]/40'
                  : 'border-[#202521]/15'
              } ${alert.isRead ? 'opacity-70' : ''}`}
            >
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-2">
                <div className="flex items-center gap-2">
                  <span
                    className={`w-2.5 h-2.5 rounded-full ${
                      isCrit ? 'bg-[#9E4939]' : isWarn ? 'bg-[#B78632]' : 'bg-[#607481]'
                    }`}
                  />
                  <span className="font-bold text-[#202521] font-sans text-sm">
                    {alert.title}
                  </span>
                  <span
                    className={`text-[9px] font-mono font-bold px-2 py-0.5 rounded uppercase ${
                      isCrit
                        ? 'bg-[#9E4939] text-[#FFFDF7]'
                        : isWarn
                        ? 'bg-[#B78632] text-[#FFFDF7]'
                        : 'bg-[#607481] text-[#FFFDF7]'
                    }`}
                  >
                    {alert.severity}
                  </span>
                </div>
                <span className="text-[11px] font-mono text-[#202521]/60">
                  {new Date(alert.createdAt).toLocaleString()}
                </span>
              </div>

              <p className="text-xs text-[#202521]/80 font-normal leading-relaxed mb-4">
                {alert.summary}
              </p>

              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pt-3 border-t border-[#202521]/10 text-xs font-mono">
                <div className="flex items-center gap-4 text-[#202521]/70">
                  <span>Facility: <strong>{alert.facilityName}</strong></span>
                  <span>•</span>
                  <span>Inspection: <strong>{alert.inspectionPriority}</strong></span>
                </div>

                <div className="flex items-center gap-3">
                  {!alert.isRead && (
                    <button
                      onClick={() => handleDismiss(alert.id)}
                      className="px-3 py-1 rounded bg-[#F4F1E8] hover:bg-[#D8D3C7]/60 text-[#202521] text-[11px] font-mono transition-colors cursor-pointer"
                    >
                      Mark Reviewed
                    </button>
                  )}
                  <Link
                    to={`/app/batches/${alert.batchId}`}
                    className="inline-flex items-center gap-1.5 px-3 py-1 rounded bg-[#26352D] hover:bg-[#202521] text-[#FFFDF7] text-[11px] font-bold font-mono transition-colors"
                  >
                    <span>Audit Batch</span>
                    <ArrowRight className="w-3 h-3" />
                  </Link>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
